name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Exécute l'action uniquement sur des push vers la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser une machine Ubuntu pour exécuter l'action

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Récupérer le code du repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Permet d'utiliser Docker Buildx pour construire l'image

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2  # Se connecter au registre Docker de GitHub
      with:
        username: ${{ github.actor }}  # Utiliser le nom d'utilisateur GitHub
        password: ${{ secrets.GITHUB_TOKEN }}  # Utiliser le jeton GitHub pour s'authentifier

    - name: Build and push Docker image
      uses: docker/build-push-action@v3  # Utiliser l'action officielle pour construire et publier l'image Docker
      with:
        context: .  # Le contexte est le répertoire actuel (racine de votre repository)
        file: ./Dockerfile  # Le fichier Dockerfile se trouve à la racine du repository
        push: true  # Pousser l'image vers le registre après la construction
        tags: ${{ github.repository }}:latest  # Tag de l'image, ici on utilise le nom du repository comme tag
